// When the script runs, the browser caches content generated by the script, such as this template. Cached elements speed up page loading times.
// #1 Note that when naming action-oriented functions, it's a convention to start the function name with a verb.
// This function returns the markup string as a jQuery object
var buildCollectionItemTemplate = function() {
     var template =
    '<div class="collection-album-container column fourth">'
  + '  <img src="images/album_covers/01.png"/>'
  + '  <div class="collection-album-info caption">'
  + '    <p>'
  + '      <a class="album-name" href="album.html"> The Colors </a>'
  + '      <br/>'
  + '      <a href="album.html"> Pablo Picasso </a>'
  + '      <br/>'
  + '      X songs'
  + '      <br/>'
  + '    </p>'
  + '  </div>'
  + '</div>'
  ;

// #2 wrap template in a jQuery object
  return $(template);
};




$(window).load(function() {
     // #3 When the element section becomes a jQuery object, prefix the [collectionContainer] variable with a $. This identifies jQuery-related variables. Consistency!
     var $collectionContainer = $('.album-covers');
     // #4 empty() method removes everything from the element it is called on
     $collectionContainer.empty();

     // insert 12 albums
     for (var i = 0; i < 12; i++) {
       var $newThumbnail = buildCollectionItemTemplate();
     // #5 With each loop, append the template content to the collectionContainer
     $collectionContainer.append($newThumbnail);
     }
 });
