// When the script runs, the browser caches content generated by the script, such as this template. Cached elements speed up page loading times.
var collectionItemTemplate =
    '<div class="collection-album-container column fourth">'
  + '  <img src="assets/images/album_covers/01.png"/>'
  + '  <div class="collection-album-info caption">'
  + '    <p>'
  + '      <a class="album-name" href="album.html"> The Colors </a>'
  + '      <br/>'
  + '      <a href="album.html"> Pablo Picasso </a>'
  + '      <br/>'
  + '      X songs'
  + '      <br/>'
  + '    </p>'
  + '  </div>'
  + '</div>'
  ;

  window.onload = function() {
     // #1
     var collectionContainer = document.getElementsByClassName('album-covers')[0];
     // #2 clear content to work with a clean slate
     collectionContainer.innerHTML = '';

     // #3 insert 12 albums
     for (var i = 0; i < 12; i++) {
         collectionContainer.innerHTML += collectionItemTemplate;
     }
 }；
