// When the script runs, the browser caches content generated by the script, such as this template. Cached elements speed up page loading times.
var collectionItemTemplate =
    '<div class="collection-album-container column fourth">'
  + '  <img src="images/album_covers/01.png"/>'
  + '  <div class="collection-album-info caption">'
  + '    <p>'
  + '      <a class="album-name" href="album.html"> The Colors </a>'
  + '      <br/>'
  + '      <a href="album.html"> Pablo Picasso </a>'
  + '      <br/>'
  + '      X songs'
  + '      <br/>'
  + '    </p>'
  + '  </div>'
  + '</div>'
  ;

  window.onload = function() {
     // #1
     var collectionContainer = document.getElementsByClassName('album-covers')[0];
     // #2 clear content to work with a clean slate
     collectionContainer.innerHTML = '';

     // #3 insert 12 albums
     for (var i = 0; i < 12; i++) {
         collectionContainer.innerHTML += collectionItemTemplate;
     }
 };


// //checkpoint 24 homework

//
// //Beethoven
// var collectionItemTemplate =
//     '<div class="collection-album-container column fourth">'
//   + '  <img src="images/album_covers/09.png"/>'
//   + '  <div class="collection-album-info caption">'
//   + '    <p>'
//   + '      <a class="album-name" href="album.html"> Beethoven Symphonies </a>'
//   + '      <br/>'
//   + '      <a href="album.html">Ludwig van Beethoven</a>'
//   + '      <br/>'
//   + '      Symphony No.7'
//   + '      <br/>'
//   + '    </p>'
//   + '  </div>'
//   + '</div>'
//   ;
//
//   window.onload = function() {
//      // #1
//      var collectionContainer = document.getElementsByClassName('album-covers')[0];
//      // #2 clear content to work with a clean slate
//      collectionContainer.innerHTML = '';
//
//      // #3 insert 12 albums
//      for (var i = 0; i < 2; i++) {
//          collectionContainer.innerHTML += collectionItemTemplate;
//      }
//  };
//
//  //eventListener
//  window.addEventListener('scroll', function(event) {
//    if (document.documentElement.scrollTop || document.body.scrollTop >= scrollDistance) {
//           animatePoints(pointsArray);
//       }
// }
